import { site } from "@/content/site";

export const privacy = {
  title: "Privacy Policy",
  intro:
    "We are strongly committed to protecting the privacy of your personal information. The policies below are applicable to the Yoga Pod Gainesville website.",
  sections: [
    {
      title: "1. Purpose",
      paragraphs: [
        "This privacy policy is intended to let you know (1) the kinds of personal information we may gather during your visit to the site, (2) why we gather your information, (3) what we use your personal information for, (4) when we might disclose your personal information, and (5) how you can manage your personal information.",
        "Please be advised that the practices described in this privacy policy apply only to information we gather on our site. They do not apply to information that you provide to third party sites such as our booking provider, or any registration company we utilize to register for membership, other third parties with links on our web site, or to vendors, sponsors, partners, affiliates or social networking sites. Please review their separate privacy policies.",
      ],
    },
    {
      title: "2. Your acceptance",
      paragraphs: [
        "By visiting our site, you are accepting the practices described in our Privacy Policy. If you do not agree to the terms of our Privacy Policy, please do not use the site. We reserve the right to modify or amend the terms of our Privacy Policy from time to time without notice. Your continued use of our site following the posting of changes to these terms will mean you accept those changes.",
      ],
    },
    {
      title: "3. Contact",
      paragraphs: [
        `If you have any questions about this privacy policy, don't see your concerns addressed here, or wish to make changes to any personal information we have collected, you should contact us by email at [${site.email}](mailto:${site.email}) with the subject "Privacy Policy".`,
      ],
    },
    {
      title: "4. Information we may collect",
      paragraphs: [
        "Except as disclosed below, we don't sell, barter, give away, or rent your personal information.",
        "**Personal information.** Use of certain features of the site, like signing up to receive a newsletter, or responding to one of our surveys may require that you provide certain personally identifiable information — information that identifies or describes you, such as your name, email address, telephone numbers, address, zip code, age, and gender. We also may collect and store personal information about you that we receive from other sources.",
        "**Anonymous information.** Even if you don't request a newsletter or fill out a survey, when you interact with the site, we may collect certain non-personal information. Our servers keep an activity log that tracks all visitors to the site. The information in the activity log is anonymous and therefore does not identify you individually. It may include your IP address, our registered domain or home server, time and date of access, web pages visited, number of clicks, software crash reports, type of browser used, session identification number, search terms, search results, access times and referring website addresses.",
        "**Cookies.** We do not install spyware on your computer, nor do we use spyware to retrieve information from your computer. Like many websites, we may use cookies, which are small text files that are stored on your computer or equipment when you visit certain online pages that record your preferences. We use cookies to track your use of our website and its features, to monitor traffic, and to improve the site. You may occasionally get cookies from companies with links on our website — we do not control these cookies, and they are not subject to our privacy policy. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline them.",
        "**Analytics.** We use Google Analytics on our site. Google Analytics uses cookies to collect anonymous traffic data to help us analyze how users use the website. The information generated by a cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. By using the website, you consent to the processing of data about you by Google in the manner and for the purposes described in this Privacy Policy.",
      ],
    },
    {
      title: "5. How we may use your information",
      paragraphs: [
        "Except as disclosed in this privacy policy, we do not use or disclose information about your individual visits to our site or your personal information collected online to any parties other than those with whom we partner or are affiliated without your consent.",
        "**In general.** We use your personal information to communicate with you about your interest in our classes and our company, to help us improve your experience on the site, and in some cases to promote our events. We may also use your information to prevent or detect abuses of our terms of use and to enable third parties to carry out technical or other functions on our behalf.",
        "**Your submissions.** By giving us your personal information either through our website or email, you expressly consent to our collection, use and disclosure of your personal information as described in this privacy policy.",
        "**Third parties.** We may occasionally have third party representatives, agents, affiliates and partners that perform functions on our behalf, such as class registration, marketing, and analytics. These entities may have access to your personal information but only as needed to perform their services.",
        "**Emergency situations.** We may also use or disclose personal information if required to do so by law or in the good-faith belief that such action is necessary to conform to applicable law or comply with legal process, protect and defend our rights or property, or act under emergency circumstances to protect the personal safety of us, our affiliates, agents, the users of the site, or the public.",
      ],
    },
    {
      title: "6. Security",
      paragraphs: [
        "The security of your information is of great concern to us. We exercise care in providing secure transmission of your information from your computer to our servers. Personal information collected by our site is stored in secure operating environments that are not open to the public. While we try our best to safeguard your information once we receive it, no transmission of data over the Internet or any other public network can be guaranteed to be 100% secure.",
      ],
    },
    {
      title: "7. Linking to or from other websites",
      paragraphs: [
        "Our site contains links to other websites, and in some cases frames other websites, operated by our affiliates, partners or third parties. Please be advised that the practices described in this privacy policy do not apply to information gathered through these other websites. These other sites may also send their own cookies to you, collect your data or solicit your personal information. We are not responsible for the actions and privacy policies of third parties and other websites. We encourage you to be aware of when you leave this site and read the privacy policies of each and every website that you visit.",
      ],
    },
    {
      title: "8. Assignment",
      paragraphs: [
        "We may change our ownership or corporate organization while providing the website. As a result, please be aware that we may transfer your information to another company that is affiliated with us or with which we have merged.",
      ],
    },
    {
      title: "9. Changes to this policy",
      paragraphs: [
        "As our website continues to develop, we may change or add new services or features to our site. In the event that these additions affect our privacy policy, this document will be updated appropriately. Please check back regularly for changes.",
      ],
    },
    {
      title: "10. Managing your information and opting out",
      paragraphs: [
        `You may always opt out of receiving future email messages and newsletters from us, or request that your information be removed from our website or corrected. To make such a request, send us a message at [${site.email}](mailto:${site.email}) with the subject line "opt out".`,
      ],
    },
  ],
};
